FROM golang:latest AS build

RUN apt-get update && apt-get install -y \
    libgtk-3-dev \
    libwebkit2gtk-4.1-dev \
    nodejs \
    npm \
    && rm -rf /var/lib/apt/lists/*

RUN go install github.com/wailsapp/wails/v2/cmd/wails@v2.12.0

WORKDIR /app
COPY . .

RUN npm ci --prefix frontend

RUN VERSION=$(grep '^const AppVersion' src/version.go | sed 's/.*"\(.*\)".*/\1/') \
    && sed -i "s/\"productVersion\": \".*\"/\"productVersion\": \"$VERSION\"/" wails.json

RUN wails build -tags webkit2_41 -platform linux/amd64
