// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCorrespondent(arg1) {
  return window['go']['src']['WorkspaceBridge']['AddCorrespondent'](arg1);
}

export function CheckInitialWorkDir() {
  return window['go']['src']['WorkspaceBridge']['CheckInitialWorkDir']();
}

export function GetCorrespondents() {
  return window['go']['src']['WorkspaceBridge']['GetCorrespondents']();
}

export function GetNextPDF() {
  return window['go']['src']['WorkspaceBridge']['GetNextPDF']();
}

export function GetPdfInfo(arg1) {
  return window['go']['src']['WorkspaceBridge']['GetPdfInfo'](arg1);
}

export function SelectWorkingDirectory() {
  return window['go']['src']['WorkspaceBridge']['SelectWorkingDirectory']();
}

export function SetContext(arg1) {
  return window['go']['src']['WorkspaceBridge']['SetContext'](arg1);
}
