// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {src} from '../models';
import {context} from '../models';

export function AddCorrespondent(arg1:string):Promise<void>;

export function AnalyzePDF(arg1:string):Promise<src.Analysis>;

export function CheckArchiveConflict(arg1:string,arg2:string,arg3:string):Promise<src.MoveConflict>;

export function CheckInitialWorkDir():Promise<string>;

export function CheckTodoConflict(arg1:string,arg2:string):Promise<src.MoveConflict>;

export function CheckTrashConflict(arg1:string,arg2:string):Promise<src.MoveConflict>;

export function CreateFolder(arg1:string):Promise<void>;

export function EnsureWorkDirStructure():Promise<string>;

export function GetCorrespondentFolders():Promise<Record<string, string>>;

export function GetCorrespondents():Promise<Array<string>>;

export function GetFolderList():Promise<Array<string>>;

export function GetNextPDF():Promise<string>;

export function GetPDFPageCount(arg1:string):Promise<number>;

export function GetPdfInfo(arg1:string):Promise<src.PdfInfo>;

export function GetVersion():Promise<string>;

export function MoveFileToSystemTrash(arg1:string):Promise<void>;

export function MoveToArchiv(arg1:string,arg2:string,arg3:string):Promise<void>;

export function MoveToTodo(arg1:string,arg2:string):Promise<void>;

export function MoveToTrash(arg1:string,arg2:string):Promise<void>;

export function OpenFileInOSViewer(arg1:string):Promise<void>;

export function RemoveCorrespondent(arg1:string):Promise<void>;

export function ReorderCorrespondents(arg1:Array<string>):Promise<void>;

export function SelectWorkingDirectory():Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetCorrespondentFolder(arg1:string,arg2:string):Promise<void>;
