// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCorrespondent(arg1) {
  return window['go']['src']['WorkspaceBridge']['AddCorrespondent'](arg1);
}

export function AnalyzePDF(arg1) {
  return window['go']['src']['WorkspaceBridge']['AnalyzePDF'](arg1);
}

export function CheckArchiveConflict(arg1, arg2, arg3) {
  return window['go']['src']['WorkspaceBridge']['CheckArchiveConflict'](arg1, arg2, arg3);
}

export function CheckInitialWorkDir() {
  return window['go']['src']['WorkspaceBridge']['CheckInitialWorkDir']();
}

export function CheckTodoConflict(arg1, arg2) {
  return window['go']['src']['WorkspaceBridge']['CheckTodoConflict'](arg1, arg2);
}

export function CheckTrashConflict(arg1, arg2) {
  return window['go']['src']['WorkspaceBridge']['CheckTrashConflict'](arg1, arg2);
}

export function CreateFolder(arg1) {
  return window['go']['src']['WorkspaceBridge']['CreateFolder'](arg1);
}

export function EnsureWorkDirStructure() {
  return window['go']['src']['WorkspaceBridge']['EnsureWorkDirStructure']();
}

export function GetCorrespondentFolders() {
  return window['go']['src']['WorkspaceBridge']['GetCorrespondentFolders']();
}

export function GetCorrespondents() {
  return window['go']['src']['WorkspaceBridge']['GetCorrespondents']();
}

export function GetFolderList() {
  return window['go']['src']['WorkspaceBridge']['GetFolderList']();
}

export function GetNextPDF() {
  return window['go']['src']['WorkspaceBridge']['GetNextPDF']();
}

export function GetPDFPageCount(arg1) {
  return window['go']['src']['WorkspaceBridge']['GetPDFPageCount'](arg1);
}

export function GetPdfInfo(arg1) {
  return window['go']['src']['WorkspaceBridge']['GetPdfInfo'](arg1);
}

export function GetVersion() {
  return window['go']['src']['WorkspaceBridge']['GetVersion']();
}

export function MoveToArchiv(arg1, arg2, arg3) {
  return window['go']['src']['WorkspaceBridge']['MoveToArchiv'](arg1, arg2, arg3);
}

export function MoveToArchivOverwrite(arg1, arg2, arg3) {
  return window['go']['src']['WorkspaceBridge']['MoveToArchivOverwrite'](arg1, arg2, arg3);
}

export function MoveToTodo(arg1, arg2) {
  return window['go']['src']['WorkspaceBridge']['MoveToTodo'](arg1, arg2);
}

export function MoveToTodoOverwrite(arg1, arg2) {
  return window['go']['src']['WorkspaceBridge']['MoveToTodoOverwrite'](arg1, arg2);
}

export function MoveToTrash(arg1, arg2) {
  return window['go']['src']['WorkspaceBridge']['MoveToTrash'](arg1, arg2);
}

export function MoveToTrashOverwrite(arg1, arg2) {
  return window['go']['src']['WorkspaceBridge']['MoveToTrashOverwrite'](arg1, arg2);
}

export function OpenFileInOSViewer(arg1) {
  return window['go']['src']['WorkspaceBridge']['OpenFileInOSViewer'](arg1);
}

export function RemoveCorrespondent(arg1) {
  return window['go']['src']['WorkspaceBridge']['RemoveCorrespondent'](arg1);
}

export function ReorderCorrespondents(arg1) {
  return window['go']['src']['WorkspaceBridge']['ReorderCorrespondents'](arg1);
}

export function SelectWorkingDirectory() {
  return window['go']['src']['WorkspaceBridge']['SelectWorkingDirectory']();
}

export function SetContext(arg1) {
  return window['go']['src']['WorkspaceBridge']['SetContext'](arg1);
}

export function SetCorrespondentFolder(arg1, arg2) {
  return window['go']['src']['WorkspaceBridge']['SetCorrespondentFolder'](arg1, arg2);
}

export function WritePDFTags(arg1, arg2) {
  return window['go']['src']['WorkspaceBridge']['WritePDFTags'](arg1, arg2);
}
